const dotenv = require('dotenv');
dotenv.config();

module.exports = {
  nodeEnv: process.env.NODE_ENV || 'development',
  port: process.env.PORT || 3000,
  service: process.env.SERVICE || 'api',
  databaseUrl: process.env.DATABASE_URL,
  databaseReplicaUrl: process.env.DATABASE_REPLICA_URL,
  redisUrl: process.env.REDIS_URL,
  redisTls: process.env.REDIS_TLS === 'true',
  jwtSecret: process.env.JWT_SECRET,
  jwtRefreshSecret: process.env.JWT_REFRESH_SECRET,
  jwtAccessExpiry: process.env.JWT_ACCESS_EXPIRY || '15m',
  jwtRefreshExpiry: process.env.JWT_REFRESH_EXPIRY || '7d',
  bcryptRounds: parseInt(process.env.BCRYPT_ROUNDS) || 12,
  s3: {
    endpoint: process.env.S3_ENDPOINT,
    accessKey: process.env.S3_ACCESS_KEY,
    secretKey: process.env.S3_SECRET_KEY,
    bucket: process.env.S3_BUCKET,
    useSSL: process.env.S3_USE_SSL === 'true',
  },
  cdnUrl: process.env.CDN_URL,
  queueUrl: process.env.QUEUE_URL,
  openaiApiKey: process.env.OPENAI_API_KEY,
  aiModel: process.env.AI_MODEL || 'gpt-3.5-turbo',
  aiRateLimit: parseInt(process.env.AI_RATE_LIMIT) || 10,
  aiMaxTokens: parseInt(process.env.AI_MAX_TOKENS) || 1000,
  rateLimitWindowMs: parseInt(process.env.RATE_LIMIT_WINDOW_MS) || 60000,
  rateLimitMax: parseInt(process.env.RATE_LIMIT_MAX_REQUESTS) || 60,
  socketRateLimit: parseInt(process.env.SOCKET_RATE_LIMIT) || 10,
  uploadLimit: parseInt(process.env.UPLOAD_LIMIT) || 104857600,
  maxMessageSize: parseInt(process.env.MAX_MESSAGE_SIZE) || 10485760,
  sessionSecret: process.env.SESSION_SECRET,
  corsOrigin: process.env.CORS_ORIGIN || '*',
  logLevel: process.env.LOG_LEVEL || 'info',
};
