FROM node:18-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install --production

# Copy source
COPY . .

# Create necessary folders
RUN mkdir -p uploads logs data

# Expose port
EXPOSE 3000

# Start
CMD ["npm", "start"]
